name: docs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # enable color output from Sphinx
  FORCE_COLOR: "1"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pandoc and doxygen
        run: |
          sudo apt install pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Install ppmpy
        run: pip install --editable .

      - name: Build docs
        run: |
          jupyter-book build --all ./docs
